/* Scans skills/*.md and writes assets/js/skills-data.js containing the entire
   library (metadata + body) as `window.SKILLS`. The website loads THIS file, not
   the raw .md files — so it works on GitHub Pages even when Jekyll is active
   (Jekyll rewrites .md files but leaves .js untouched), and even from file://.

   Run:  node scripts/build-data.mjs   (also runs build-index.mjs for skills.json) */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const skillsDir = join(root, 'skills');

function parseFrontMatter(raw) {
  raw = raw.replace(/^﻿/, '').replace(/\r\n/g, '\n');
  const m = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) return { data: {}, body: raw };
  const data = {};
  for (const line of m[1].split('\n')) {
    const idx = line.indexOf(':');
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let val = line.slice(idx + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    data[key] = val;
  }
  return { data, body: m[2].trim() };
}

const files = readdirSync(skillsDir).filter(f => f.endsWith('.md') && !f.startsWith('_'));
const skills = [];

for (const file of files) {
  const raw = readFileSync(join(skillsDir, file), 'utf8');
  const { data, body } = parseFrontMatter(raw);
  const slug = basename(file, '.md');
  if (!data.title) { console.warn(`skip ${file} (no title)`); continue; }
  skills.push({
    slug,
    title: data.title,
    category: data.category || 'Uncategorised',
    summary: data.summary || '',
    trigger: data.trigger || '',
    inputs: data.inputs || '',
    connectors: data.connectors || '',
    owner: data.owner || 'Visma GTM',
    updated: data.updated || '',
    tags: (data.tags || '').split(',').map(t => t.trim()).filter(Boolean),
    body,
  });
}

skills.sort((a, b) => a.title.localeCompare(b.title));

const banner = '/* AUTO-GENERATED by scripts/build-data.mjs — do not edit by hand.\n' +
  '   Edit the Markdown files in /skills, then run: node scripts/build-data.mjs */\n';
writeFileSync(
  join(root, 'assets', 'js', 'skills-data.js'),
  banner + 'window.SKILLS = ' + JSON.stringify(skills, null, 2) + ';\n'
);
console.log(`✓ Wrote assets/js/skills-data.js with ${skills.length} skill(s).`);
